### ISSUE TITLE
Broken DB after hard-reboot

### ISSUE THREAD

**Issue by petrkr** [kyuupichan/electrumx#95] opened 2017-01-05 14:04 UTC
Today my server somehow self-rebooted hard and it probably corrupted RocksDB on electrumx node.
Do not know if there is some way how to chase that (like rewind some blocks and do them again) or something what will preserve for whole rescan, it does not took such long but still it is like 22hours.

>electrum@server ~ $ cat btc-mainnet-server.sh 
>#!/bin/bash
>echo "Setting up environment"
>
>export COIN=Bitcoin
>export DAEMON_URL=http://user:pass@localhost
>export NETWORK=mainnet
>export DB_ENGINE=rocksdb
>export DB_DIRECTORY=/mnt/ssd/electrumx/
>
>export HOST=0.0.0.0
>export TCP_PORT=50001
>export SSL_PORT=50002
>
>export SSL_CERTFILE="/etc/electrum/server.crt"
>export SSL_KEYFILE="/etc/electrum/server.key"
>
>export BANNER_FILE="/etc/electrum/electrum.banner"
>export DONATION_ADDRESS="15zN5qAN5sHYfMQB8ckpsNPFT2tjtwtGA8"
>
>export IRC="yes"
>export IRC_NICK="petrkr"
>export REPORT_HOST="electrum.petrkr.net"
>
>echo "Running server"
>python3.5 /usr/bin/electrumx_server.py``

>electrum@server ~ $ ./btc-mainnet-server.sh 
>Setting up environment
>Running server
>INFO:root:ElectrumX server starting
>INFO:BlockProcessor:switching current directory to /mnt/ssd/electrumx/
>INFO:BlockProcessor:reorg limit is 200 blocks
>INFO:BlockProcessor:opened rocksdb database Bitcoin-mainnet for serving
>INFO:BlockProcessor:software version: ElectrumX 0.9.22
>INFO:BlockProcessor:DB version: 3
>INFO:BlockProcessor:coin: Bitcoin
>INFO:BlockProcessor:network: mainnet
>INFO:BlockProcessor:height: 446,733
>INFO:BlockProcessor:tip: 000000000000000000d8a940e0a228725b86afd37c4828ec83e450cf073fb844
>INFO:BlockProcessor:tx count: 185,016,601
>Traceback (most recent call last):
>  File "/usr/lib64/python3.5/site-packages/electrumx-0.9.22-py3.5.egg/EGG-INFO/scripts/electrumx_server.py", line 69, in main
>  File "/usr/lib64/python3.5/site-packages/electrumx-0.9.22-py3.5.egg/EGG-INFO/scripts/electrumx_server.py", line 50, in main_loop
>  File "/usr/lib64/python3.5/site-packages/electrumx-0.9.22-py3.5.egg/server/controller.py", line 51, in __init__
>    self.bp = BlockProcessor(env)
>  File "/usr/lib64/python3.5/site-packages/electrumx-0.9.22-py3.5.egg/server/block_processor.py", line 162, in __init__
>    super().__init__(env)
>  File "/usr/lib64/python3.5/site-packages/electrumx-0.9.22-py3.5.egg/server/db.py", line 67, in __init__
>    assert self.db_tx_count == self.tx_counts[-1]
>AssertionError
CRITICAL:root:ElectrumX server terminated abnormally

Using RocksDB version from GIT
>git clone https://github.com/facebook/rocksdb.git
>git reset --hard 8d7926a766f2ab9bd6e7aa8cba80b5d3ff26c52b

**Comment by kyuupichan** [comment] 2017-01-08 09:24
You can see at

https://github.com/kyuupichan/electrumx/blob/master/server/storage.py#L108

we set use_fsync=True.  According to RocksDB docs,

http://pyrocksdb.readthedocs.io/en/v0.4/api/options.html#rocksdb.Options.use_fsync

this should be enough to guarantee on-disk consistency.

There is nothing else that ElectrumX can set or control here I think.  Perhaps RocksDB or the O/S and filesystem setup you have is part of the problem.

FWIW I've not yet had a report of this happening with LevelDB, but that may be chance.

I will close this because I don't think there is any more I can do; if you think RocksDB offers some other consistency API please re-open this.

**Closed by kyuupichan** 2017-01-08 09:24 UTC

**Comment by metamarcdw** [comment] 2017-07-30 00:07
Believe I'm having this same issue, also after a hard reboot. Using LevelDB:

-- Logs begin at Sat 2017-07-29 18:40:24 CDT. --
Jul 29 18:40:44 ubuntu-electrumx electrumx_server.py[1022]:   File "/home/electrumx/electrumx/electrumx_server.py", line 56, in main_loop
Jul 29 18:40:44 ubuntu-electrumx electrumx_server.py[1022]:     controller = Controller(Env())
Jul 29 18:40:44 ubuntu-electrumx electrumx_server.py[1022]:   File "/home/electrumx/electrumx/server/controller.py", line 51, in __init__
Jul 29 18:40:44 ubuntu-electrumx electrumx_server.py[1022]:     self.bp = self.coin.BLOCK_PROCESSOR(env, self, self.daemon)
Jul 29 18:40:44 ubuntu-electrumx electrumx_server.py[1022]:   File "/home/electrumx/electrumx/server/block_processor.py", line 144, in __init__
Jul 29 18:40:44 ubuntu-electrumx electrumx_server.py[1022]:     super().__init__(env)
Jul 29 18:40:44 ubuntu-electrumx electrumx_server.py[1022]:   File "/home/electrumx/electrumx/server/db.py", line 90, in __init__
Jul 29 18:40:44 ubuntu-electrumx electrumx_server.py[1022]:     assert self.db_tx_count == self.tx_counts[-1]
Jul 29 18:40:44 ubuntu-electrumx electrumx_server.py[1022]: AssertionError
Jul 29 18:40:44 ubuntu-electrumx electrumx_server.py[1022]: CRITICAL:root:ElectrumX server terminated abnormally

Any idea how I can recover my server? Should I delete the db directory?

**Comment by oginiwaro-9681** [comment] 2018-10-01 10:43
I can confirm this on latest version (1.8.7) + Bitcoin mainnet. Currently not a big problem because database size is relatively small, but later the problem could get bigger.

**Comment by ulrichard** [comment] 2018-10-27 20:37
I am getting the same assert when starting electrumx for Bitcoin mainnet with LevelDB after a power outage. Is there anything I can do other than deleting the DB and reindexing the whole thing again?

**Comment by kyuupichan** [comment] 2018-10-28 02:33
Nope.  Unfortunately corrupt DBs are because the hardware, O/S, DB software, or ElectrumX is lying to you about its guarantees.  I'm not sure which.

**Comment by kyuupichan** [comment] 2018-10-28 02:36
It could also be your O/S settings/config.  There are too many variables unfortunately to really know what's going on in these cases.

**Comment by kyuupichan** [comment] 2018-10-28 02:36
Like for example, your filesystem settings on mount.
