### ISSUE TITLE
Assertion error when starting the electrumx server

### ISSUE THREAD

**Issue by Souvikray** [kyuupichan/electrumx#344] opened 2018-01-05 06:00 UTC
Whenever I fire up the electrumx server, it gives an assertion error message.On searching the issue elsewhere, it seems the problem could vary anywhere between the version of leveldb to value of the NET variable.I have tried downgrading the leveldb version, gave all possible values to NET variable, introduced a Deserializer to the coin definition but nothiing helped.Below is the traceback

```
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:root:ElectrumX server starting
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:Controller:event loop policy: None
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:Daemon:daemon #1 at localhost:7313/ (current)
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:switching current directory to /home/souvik/.electrumx/
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:using leveldb for DB backend
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:opened DB for serving
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:closing DB to re-open for sync
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:opened DB for sync
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:software version: ElectrumX 1.2.1
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:DB version: 6
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:coin: Florincoin
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:network: mainnet
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:height: 589
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:tip: 24fc62e33e690e56a8b9443f4c3c7e99467590c5c3fcf5287d5875f969a0eda4
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:tx count: 589
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:flush count: 9
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:sync time so far: 04h 50m 07s
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:reorg limit is 800 blocks
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:BlockProcessor:flushing DB cache at 1,800 MB
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:Controller:RPC server listening on localhost:8000
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: INFO:Prefetcher:catching up to daemon height 2,529,192 (2,528,603 blocks behind)
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: ERROR:Controller:Traceback (most recent call last):
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:   File "/home/souvik/source/electrumx/server/controller.py", line 177, in on_future_done
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:     future.result()
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:   File "/usr/lib/python3.6/asyncio/tasks.py", line 239, in _step
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:     result = coro.send(None)
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:   File "/home/souvik/source/electrumx/server/block_processor.py", line 206, in main_loop
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:     await task()
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:   File "/home/souvik/source/electrumx/server/block_processor.py", line 243, in check_and_advance_blocks
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:     for n, raw_block in enumerate(raw_blocks)]
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:   File "/home/souvik/source/electrumx/server/block_processor.py", line 243, in <listcomp>
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:     for n, raw_block in enumerate(raw_blocks)]
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:   File "/home/souvik/source/electrumx/lib/coins.py", line 272, in block
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:     txs = cls.DESERIALIZER(raw_block, start=len(header)).read_tx_block()
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:   File "/home/souvik/source/electrumx/lib/tx.py", line 103, in read_tx_block
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:     txs = [read_tx() for _ in range(self._read_varint())]
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:   File "/home/souvik/source/electrumx/lib/tx.py", line 103, in <listcomp>
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:     txs = [read_tx() for _ in range(self._read_varint())]
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:   File "/home/souvik/source/electrumx/lib/tx.py", line 220, in read_tx
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:     inputs = self._read_inputs()
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:   File "/home/souvik/source/electrumx/lib/tx.py", line 109, in _read_inputs
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:     return [read_input() for i in range(self._read_varint())]
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:   File "/home/souvik/source/electrumx/lib/tx.py", line 109, in <listcomp>
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:     return [read_input() for i in range(self._read_varint())]
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:   File "/home/souvik/source/electrumx/lib/tx.py", line 113, in _read_input
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:     self._read_nbytes(32),   # prev_hash
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:   File "/home/souvik/source/electrumx/lib/tx.py", line 137, in _read_nbytes
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]:     assert self.binary_length >= end
Jan  5 11:29:04 souvik-Lenovo-ideapad-500S-14ISK electrumx_server.py[5693]: AssertionError
```

What could be going wrong?

**Comment by kyuupichan** [comment] 2018-01-05 07:06
Florincoin is apparently not implemented correctly.  This is a duplicate of #334.  Someone who cares about that coin will have to fix it.

**Closed by kyuupichan** 2018-01-05 07:06 UTC
