### ISSUE TITLE
struct.error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)

### ISSUE THREAD

**Issue by maff1989** [kyuupichan/electrumx#573] opened 2018-08-14 07:38 UTC
Some info on my setup:

Ubuntu 16.04.5 LTS Xenial
INFO:Controller:Python version: 3.6.5 (default, May  3 2018, 10:08:28) 
[GCC 5.4.0 20160609]
INFO:Controller:software version: ElectrumX 1.8.3
INFO:Controller:aiorpcX version: 0.7.1
INFO:Controller:supported protocol versions: 1.1-1.4
INFO:Controller:event loop policy: None
INFO:Controller:reorg limit is 200 blocks

I added Zcoin support to electrumx/lib/coins.py, but other than that I have not changed any code.

The server starts up fine, syncs with the Zcoin daemon, and runs flawlessly. I can use the Electrum client and connect to the instance, submit transactions, etc.  However after a seemingly random period of time, the ElectrumX server crashes:

```
ERROR:root:task crashed: <Task finished coro=<MemPool._fetch_and_accept() done, defined at /root/electrumx/electrumx/server/mempool.py:257> exception=error('ushort format requires 0 <= number <= (0x7fff * 2 + 1)',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/util.py", line 118, in check_task
    task.result()
  File "/root/electrumx/electrumx/server/mempool.py", line 292, in _fetch_and_accept
    utxos = await self.api.lookup_utxos(prevouts)
  File "/root/electrumx/electrumx/server/db.py", line 645, in lookup_utxos
    hashX_pairs = await run_in_thread(lookup_hashXs)
  File "/usr/local/lib/python3.6/dist-packages/aiorpcx/curio.py", line 61, in run_in_thread
    return await get_event_loop().run_in_executor(None, func, *args)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/electrumx/electrumx/server/db.py", line 624, in lookup_hashXs
    return [lookup_hashX(*prevout) for prevout in prevouts]
  File "/root/electrumx/electrumx/server/db.py", line 624, in <listcomp>
    return [lookup_hashX(*prevout) for prevout in prevouts]
  File "/root/electrumx/electrumx/server/db.py", line 610, in lookup_hashX
    idx_packed = pack('<H', tx_idx)
struct.error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)
```

There are more traces and I can provide them on request; I figured this would be sufficient to start. If you need anymore info on my config I can provide that too

Thanks in advance

**Comment by kyuupichan** [comment] 2018-08-14 09:04
Duplicate of https://github.com/kyuupichan/electrumx/issues/570 I think.  These coins have never processed the mempool properly, but it used to fall silently

**Comment by maff1989** [comment] 2018-08-14 09:26
Yeah, it looks like I indeed duplicated #570. Looks like an issue caused by specific transactions. I would be fine if the error fell silently, but it is crashing my instance to the point of manual intervention :/

**Comment by kyuupichan** [comment] 2018-08-18 01:53
Closing - #570 was fixed.  If you still have issues please reopen

**Closed by kyuupichan** 2018-08-18 01:53 UTC
