### ISSUE TITLE
ElectrumX stopped accepting SSL connections and failed PeerManager verifications

### ISSUE THREAD

**Issue by darthginger** [kyuupichan/electrumx#313] opened 2017-11-15 13:52 UTC
After self-compiling leveldb 1.18, i got electrumx working perfectly with hundreds of SSL and TCP connections coming in. 
Next day i check back and there are only a few connections left and only a few TCP new ones. Using my own Electrum client i can confirm only TCP works.
Electrumx didn't restart in that time frame, so i did it and i got these messages:

`INFO:PeerManager:failed connecting to xxxxxx.xx at SSL port 50002 in 0.1s: getsockaddrarg() takes exactly 2 arguments (4 given)`

Both for TCP and SSL peers.
When trying to connect via SSL there is nothing in the server logs.
With TCP the usual: `INFO:ElectrumX:[1] TCP [::1]:44102, 2 total`

**Comment by kyuupichan** [comment] 2017-11-16 17:37
Perhaps your open file limit is too low?  #94 is an SSL bug in asyncio in Python that gradually leaks open files.  If you restart the server it should be good.

But there is not enough info in your report to really be sure what happened.  The error about argument mismatch shouldn't happen and indicates something may be messed up in your Python installation.

**Comment by darthginger** [comment] 2017-11-16 19:09
Thanks for replying. A simple restart of electrumx did not help get SSL functionality back, but restarting the whole machine did and im quickly getting 100+ SSL connections!
 I increased the open file limit to 16k (was 8k), is that enough?
The problem with the 4 arguments instead of 2 is still occuring and i don't know why.
Im using python 3.6.3 on debian buster x64.
How can i provide more information?

**Comment by kyuupichan** [comment] 2017-11-16 20:24
8k should have been plenty.  I suspect the issue is something else - a reboot fixing it is very weird.

I'm afraid I have no idea what is causing the getsockaddr problem.  It is not a call made directly in ElectrumX.

**Comment by darthginger** [comment] 2017-11-16 21:00
hm maybe it has something to do with my setup? 
Electrumx runs at home with a reverse ssh tunnel to my vps that uses a letsencrypt cert.
REPORT_HOST=domainof.vps
ssh tunnel uses ipv6.

**Comment by darthginger** [comment] 2017-11-18 09:09
Electrumx stopped accepting SSL connections again, but i found the problem. It is indeed the reverse SSH tunnel thats causing trouble. After killing autossh and starting a fresh tunnel SSL worked again without even restarting electrumx.

**Comment by kyuupichan** [comment] 2017-11-18 11:42
OK so this seems to be an issue with other software, so I'll close this.

**Closed by kyuupichan** 2017-11-18 11:42 UTC
