### ISSUE TITLE
Dash: struct.error: 'H' format requires 0 <= number <= 65535

### ISSUE THREAD

**Issue by santzi** [kyuupichan/electrumx#193] opened 2017-06-17 07:55 UTC
I have got this several times during shutdown procedure and next start will fail to same reason.
Then I need to take my backup to use and then all working fine until next shutdown.

Jun 17 10:14:06 ubuntu systemd[1]: Stopping Electrumx-dash...
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]: WARNING:root:received SIGTERM signal, initiating shutdown
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]: INFO:Controller:shutting down
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]: INFO:Controller:closing down SSL, RPC, TCP listening servers
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]: INFO:PeerManager:wrote out 12 peers
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]: INFO:BlockProcessor:flushing state to DB for a clean shutdown...
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]: Traceback (most recent call last):
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.11-py3.5.egg/EGG-INFO/scripts/electrumx_server.py", line 75, in main
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:     main_loop()
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.11-py3.5.egg/EGG-INFO/scripts/electrumx_server.py", line 66, in main_loop
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:     loop.run_until_complete(future)
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:     return future.result()
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/asyncio/futures.py", line 293, in result
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:     raise self._exception
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:     result = coro.send(None)
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.11-py3.5.egg/server/controller.py", line 208, in main_loop
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:     await self.shutdown()
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.11-py3.5.egg/server/controller.py", line 238, in shutdown
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:     self.bp.shutdown(self.executor)
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.11-py3.5.egg/server/block_processor.py", line 210, in shutdown
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:     self.flush(True)
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.11-py3.5.egg/server/block_processor.py", line 366, in flush
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:     self.flush_history(self.history)
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.11-py3.5.egg/server/db.py", line 437, in flush_history
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]:     flush_id = pack('>H', self.flush_count)
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]: struct.error: 'H' format requires 0 <= number <= 65535
Jun 17 10:14:06 ubuntu electrumx_server.py[1521]: CRITICAL:root:ElectrumX server terminated abnormally
Jun 17 10:14:07 ubuntu electrumx_server.py[1521]: Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Jun 17 10:14:07 ubuntu electrumx_server.py[1521]: Traceback (most recent call last):
Jun 17 10:14:07 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/asyncio/base_events.py", line 510, in __del__
Jun 17 10:14:07 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/asyncio/unix_events.py", line 65, in close
Jun 17 10:14:07 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/asyncio/unix_events.py", line 146, in remove_signal_handler
Jun 17 10:14:07 ubuntu electrumx_server.py[1521]:   File "/usr/local/lib/python3.5/signal.py", line 47, in signal
Jun 17 10:14:07 ubuntu electrumx_server.py[1521]: TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
Jun 17 10:14:07 ubuntu systemd[1]: Stopped Electrumx-dash.

- Logs begin at Sat 2017-06-17 10:34:29 EEST. --
Jun 17 10:37:19 ubuntu systemd[1]: Started Electrumx-dash.
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:root:ElectrumX server starting
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:DashDaemon:daemon #1 at 172.16.238.1:9998/ (current)
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:switching current directory to /home/jani/debian_shares/electrumx_db/DASH/
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:using leveldb for DB backend
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:opened DB for serving
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:software version: ElectrumX 1.0.11
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:DB version: 5
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:coin: Dash
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:network: mainnet
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:height: 687,978
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:tip: 0000000000004bc482dbd5367831e5eb0e68c8e8b03f49419d7f70907c17b77c
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:tx count: 2,985,315
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:deleted 269 stale undo entries
Jun 17 10:37:22 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:reorg limit is 125 blocks
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:PeerManager:accepted new peer 1/1 electrum-dash.us.to from env
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:PeerManager:accepted new peer 1/11 hv7uixpcszokw2km.onion from peers file
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:PeerManager:accepted new peer 2/11 electrum.dash.siampm.com from peers file
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:PeerManager:accepted new peer 3/11 ele.coinpools.de from peers file
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:PeerManager:accepted new peer 4/11 dashcrypto.space from peers file
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:PeerManager:accepted new peer 5/11 dash5bugdtjex3wn.onion from peers file
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:PeerManager:accepted new peer 6/11 t3zz5w6tngiqgxlf.onion from peers file
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:PeerManager:accepted new peer 7/11 eywr5eubdbbe2laq.onion from peers file
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:PeerManager:accepted new peer 8/11 wl4sfwq2hwxnodof.onion from peers file
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:PeerManager:accepted new peer 9/11 178.62.234.69 from peers file
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:PeerManager:accepted new peer 10/11 laflsbvmfowdvsq5.onion from peers file
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:PeerManager:accepted new peer 11/11 electrum-drk.club from peers file
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:Controller:RPC server listening on localhost:8010
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:Prefetcher:catching up to daemon height 688,141 (163 blocks behind)
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:our height: 687,988 daemon: 688,141 UTXOs 0MB hist 0MB
Jun 17 10:37:23 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:processed 10 blocks in 0.5s
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]: INFO:BlockProcessor:processed 153 blocks in 2.4s
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]: ERROR:Controller:Traceback (most recent call last):
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.11-py3.5.egg/server/controller.py", line 157, in on_future_done
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:     future.result()
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:   File "/usr/local/lib/python3.5/asyncio/futures.py", line 293, in result
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:     raise self._exception
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 241, in _step
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:     result = coro.throw(exc)
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.11-py3.5.egg/server/block_processor.py", line 201, in main_loop
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:     await task()
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.11-py3.5.egg/server/block_processor.py", line 216, in first_caught_up
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:     await self.controller.run_in_executor(self.flush, True)
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.11-py3.5.egg/server/controller.py", line 137, in run_in_executor
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:     return await self.loop.run_in_executor(None, func, *args)
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:   File "/usr/local/lib/python3.5/asyncio/futures.py", line 380, in __iter__
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:     yield self  # This tells Task to wait for completion.
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:     future.result()
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:   File "/usr/local/lib/python3.5/asyncio/futures.py", line 293, in result
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:     raise self._exception
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:   File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:     result = self.fn(*self.args, **self.kwargs)
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.11-py3.5.egg/server/block_processor.py", line 366, in flush
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:     self.flush_history(self.history)
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:   File "/usr/local/lib/python3.5/site-packages/electrumx-1.0.11-py3.5.egg/server/db.py", line 437, in flush_history
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]:     flush_id = pack('>H', self.flush_count)
Jun 17 10:37:26 ubuntu electrumx_server.py[1397]: struct.error: 'H' format requires 0 <= number <= 65535
Jun 17 10:37:28 ubuntu electrumx_server.py[1397]: INFO:Prefetcher:new block height 688,142 hash 0000000000003959e592a1d9f7635218f3219649d626c28e462e88ddb0359177

**Comment by bauerj** [comment] 2017-06-17 09:59
Duplicate of #185

**Comment by kyuupichan** [comment] 2017-06-17 10:07
You need to start from scratch unfortunately. 

I'll be releasing a tool soon that you can run when ElectrumX is off to compact the history DB,which solves this problem. I'm testing it at the moment. 

Once that it working reliably for others I'll make it happen in the background whilst ElectrumX is running.

**Comment by kyuupichan** [comment] 2017-06-18 23:21
If you still have the DB, you can try the compact-hist script from 2f26e8162924cce0979d18cf622adf13a82eda57.  Once I have a couple of reports it works I'll have it run in the background of a running server.

**Comment by santzi** [comment] 2017-06-21 02:08
unfortunately I have deleted that DB, but let's wait that issue occurred again.

**Comment by kyuupichan** [comment] 2017-07-06 05:23
Clong as a duplicate of #185. I will close that once I get this happening automatically; until then you can run the script when the server is shut down.

**Closed by kyuupichan** 2017-07-06 05:23 UTC
