### ISSUE TITLE
PeerManager errors on IPv6

### ISSUE THREAD

**Issue by gits7r** [kyuupichan/electrumx#137] opened 2017-02-23 11:54 UTC
I am getting some errors related to IPv6 and some marked 'Multiple Exceptions':

I have no IPv6 connectivity on this server. Would it make sense to ignore IPv6 peers (we could advertise them further, but not try to connect to them) when IPv6 is not available?

INFO:PeerManager:failed connecting to 2a01:4f8:141:13ad::c451 at TCP port 50001: [Errno 101] Network is unreachable

And also on IPv4 getting network unreachable in rare cases (I guess this is maybe a hardcoded peer that might be down at the particular moment):
INFO:PeerManager:failed connecting to electrum.stoff-sammlung.de at SSL port 50002: Multiple exceptions: [Errno 111] Connect call failed ('148.251.6.18', 50002), [Errno 101] Network is unreachable

**Comment by kyuupichan** [comment] 2017-02-23 13:04
Those are expected in that it's normal for unreachable peers. If you know how to reliably determine existence of IPV6 connectivity I could suppress attempts, but I don't know of a way.

**Comment by kyuupichan** [comment] 2017-02-25 15:07
Closing because it's expected logging output; not a bug and not something going wrong.

If someone thinks we should not be trying IPv6 peers after somehow determining lack of IPv6 connectivity that should be done as a separate issue, preferably with a suggested way for determining that lack of connectivity.  I don't care sufficiently to change the current behaviour but could be persuaded if others disagree.

**Closed by kyuupichan** 2017-02-25 15:07 UTC
