### ISSUE TITLE
Scripthash subscribe and mempool query not working if non standard script in input

### ISSUE THREAD

**Issue by zhuyaokun** [kyuupichan/electrumx#1050] opened 2021-05-02 07:30 UTC
If tx input includes a nonstandard script, blockchain.scripthash.subscribe will not send notification. and blockchain.scripthash.mempool can not find it. Please fix it.

https://test.whatsonchain.com/tx/54153f871cb59cd7276e944b8702eeab9dbd74e89249a32fa3c6b0a1506225c8

My test way like this - I created a tx1, input is standard pk2pkh, output is one nonstandard(index 0), one is my address (index 1) and one is change address(index 2). I subscribed my address n2VYzYYny16FjB22RQo8ASsgaz564MwJ72. Then I send this tx. Subscribe, mempool and Electrum sv all can find the tx immediately. But if I create tx2 to unlock the nonstandard utxo in tx1, output is still including my address. blockchain.scripthash.subscribe, blockchain.scripthash.mempool and ec all cannot find it in time until I list transaction history by blockchain.scripthash.histroy.

**Comment by zhuyaokun** [comment] 2021-05-02 07:44
![image](https://user-images.githubusercontent.com/16613259/116806076-4271e200-ab5d-11eb-8811-d94215490f35.png)

**Comment by zhuyaokun** [comment] 2021-05-02 08:09
![image](https://user-images.githubusercontent.com/16613259/116806596-c7aac600-ab60-11eb-98e4-b89996e00753.png)

**Comment by kyuupichan** [comment] 2021-05-02 21:33
Given the way e-x works - it knows nothing about standard and non-standard; P2PKH or anything like that -  that's all in your imagination - I am 99% certain your interpretation of what is happening is wrong.  But if you still think you are right, please provide an example that is not described by screenshots I cannot understand.  I need something with clear reproducible steps.

**Comment by kyuupichan** [comment] 2021-05-02 21:35
And the reproduction steps must include what you did, i.e. what you subscribed to (precisely), not just what you observed.

**Comment by kyuupichan** [comment] 2021-05-02 21:37
I'm suspcious you do not understand, because you said "this is my subscribe", circling an address, but that's not what you subscribe to.  You subscribe to a script hash.  So this is why I want clear, unambiguous steps.

**Comment by zhuyaokun** [comment] 2021-05-03 16:36
OK. I give you a test example
scripthash: cc8b96f3c41f6ccc688b2a692c3548f6510e0dbfd92e3fa4156789581c9d7800 (scripthash of address n2VYzYYny16FjB22RQo8ASsgaz564MwJ72)
tx in the tx.txt file (it's offline tx, I didn't send it to online. You can send it to testnet to see the problem. I used 'tsv.usebsv.com:51002' and 'tls')
[tx.txt](https://github.com/kyuupichan/electrumx/files/6416206/tx.txt)

**Comment by zhuyaokun** [comment] 2021-05-03 16:51
maybe there is one possible, the test node server didn't relay the tx so e-x didn't received it. the tx size is big more than 12K.

**Comment by baryon** [comment] 2021-11-12 06:20
we didn't meet this issue. close it please

**Closed** 2021-11-12 10:04 UTC
