### ISSUE TITLE
Whitelist bypassing resource limits needed

### ISSUE THREAD

**Issue by peleion** [kyuupichan/electrumx#805] opened 2019-04-23 13:23 UTC
The most recent ElectrumX cuts off all Tor/Tails users for a particular exit node IP after a cumulative resource limit is reached and no further Tor/Tails clients can then connect to that server. Once the available pool of public Electrum servers have all reached this limit the Tor/Tails user is effectively locked out from using the wallet at all - this is a significant problem for the future use of Electrum with Tor/Tails at least until individual client authentication is available. Unfortunately the only current solution seems to be either a) run a private Electrum server or b) use Electrum on a platform other than Tails.

A whitelist file of client IPs in subnet form that bypasses the resource limit checks similar to current peer blacklist processing at initial connect would alleviate this problem allowing server OPs to decide individually whether to serve this user base. Server OPs could populate this list with the Tor exit node list or just add their own individual IPs based on their need. 

The secondary effect of this problem is that server OPs may elect to not expose their server to the public pool further reducing the public network capacity that is already diminished by the ongoing DDoS attack. This is exactly why I recently removed my server from the public pool - I use Electrum via Tails and am unwilling to run separate public and private servers. My E-X served ~2,500 clients at any given time and processed over 600 transactions per day - that capacity is now unavailable to public users. I suspect there may be other silent E-X users that have come to this same conclusion.

**Comment by kyuupichan** [comment] 2019-04-24 13:53
Duplicate of #303

**Closed by kyuupichan** 2019-04-24 13:53 UTC
Labels: duplicate
