### ISSUE TITLE
struct.error: 'H' format requires 0 <= number <= 65535

### ISSUE THREAD

**Issue by cipig** [kyuupichan/electrumx#286] opened 2017-10-10 17:19 UTC
I discovered that the electrumx server for DGB was lagging behind the daemon on 2 servers:
"daemon_height": 5348549,
"db_height": 5337273,

I then decided to stop electrumx and start again, but it gave me an error on stop:

```
WARNING:Controller:received SIGTERM signal, initiating shutdown
INFO:Controller:shutting down
INFO:Controller:closing down TCP, RPC listening servers
INFO:BlockProcessor:flushing state to DB for a clean shutdown...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/EGG-INFO/scripts/electrumx_server.py", line 25, in main
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/server/controller.py", line 937, in run
    loop.run_until_complete(future)
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25636)
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:109407)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:108946)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:112715)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/server/controller.py", line 218, in main_loop
    await self.shutdown()
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/server/controller.py", line 248, in shutdown
    self.bp.shutdown(self.executor)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/server/block_processor.py", line 215, in shutdown
    self.flush(True)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/server/block_processor.py", line 373, in flush
    self.flush_history(self.history)
  File "/usr/local/lib/python3.5/dist-packages/electrumx-1.1-py3.5.egg/server/db.py", line 454, in flush_history
    flush_id = pack('>H', self.flush_count)
struct.error: 'H' format requires 0 <= number <= 65535
CRITICAL:root:ElectrumX server terminated abnormally
```
And starting again is also not possible, electrumx dies with segv:

```
electrumx_server.py[36151]: INFO:root:ElectrumX server starting
electrumx_server.py[36151]: INFO:Controller:event loop policy: <uvloop.EventLoopPolicy object at 0x7fa88fc7d9b0>
electrumx_server.py[36151]: INFO:Daemon:daemon #1 at 127.0.0.1:14022/ (current)
electrumx_server.py[36151]: INFO:BlockProcessor:switching current directory to /home/flow/electrumdb_DGB
electrumx_server.py[36151]: INFO:BlockProcessor:using leveldb for DB backend
electrumx_server.py[36151]: INFO:BlockProcessor:opened DB for serving
electrumx_server.py[36151]: INFO:BlockProcessor:software version: ElectrumX 1.1.1
electrumx_server.py[36151]: INFO:BlockProcessor:DB version: 5
electrumx_server.py[36151]: INFO:BlockProcessor:coin: DigiByte
electrumx_server.py[36151]: INFO:BlockProcessor:network: mainnet
electrumx_server.py[36151]: INFO:BlockProcessor:height: 5,337,273
electrumx_server.py[36151]: INFO:BlockProcessor:tip: 5fe1aa2245215579765e56c305d6e06f4c892f666b89f2dc2abb2896955e3930
electrumx_server.py[36151]: INFO:BlockProcessor:tx count: 10,471,637
electrumx_server.py[36151]: INFO:BlockProcessor:flush count: 65,535
systemd[1]: electrumx_DGB.service: Main process exited, code=killed, status=11/SEGV
systemd[1]: electrumx_DGB.service: Unit entered failed state.
systemd[1]: electrumx_DGB.service: Failed with result 'signal'.
```

**Comment by bauerj** [comment] 2017-10-10 20:56
Your database exceeded the maximum flush count. electrumx should compact the database before that happens but obviously that's not the case here.

**Comment by kyuupichan** [comment] 2017-10-10 23:52
Closing as duplicate of #185.

You need to run the compact_history script then your DB will be usable again.

**Closed by kyuupichan** 2017-10-10 23:52 UTC
