### ISSUE TITLE
All peers get stale sometimes

### ISSUE THREAD

**Issue by bauerj** [kyuupichan/electrumx#135] opened 2017-02-22 16:26 UTC
The issue (the server only showing 4 `.onion` peers) we've seen on @cluelessperson's server a few days ago occured again. 

@lahlor saw this on @SuBPaR42's server today:

![2](https://cloud.githubusercontent.com/assets/598790/23220397/2ff04230-f922-11e6-9906-ade4afca0b5d.PNG)

@shsmith  saw this on his server:

![electrumx_peers-week](https://cloud.githubusercontent.com/assets/598790/23220314/dbc58fbc-f921-11e6-966f-d83a29249ed7.png)

If that happened on @SuBPaR42's server too, it would explain why the servers are missing from the output.

**Comment by kyuupichan** [comment] 2017-02-22 20:34
Why does this happen? It should be clear from the logs

**Comment by kyuupichan** [comment] 2017-02-22 22:35
Besides pertinent log information, what version of ElectrumX was being run? What was the output of peers local RPC call?

**Comment by fr3aker** [comment] 2017-02-22 23:03
I am seeing the exactly same four peers on my eletrumx server as shown on the screenshot above. Here are all PeerManager log entries since the server start: https://gist.github.com/fr3aker/893581516903cbb3ff9cd8a0c484063e

**Comment by kyuupichan** [comment] 2017-02-22 23:16
What is your peers output?

**Comment by fr3aker** [comment] 2017-02-22 23:20
edited my post above. Is that what you are looking for?

> The Controller log entry shows many stale peers:
> 
>     "peers": {"bad": 13, "stale": 62, "good": 0, "never": 2, "total": 77}

**Comment by kyuupichan** [comment] 2017-02-22 23:21
No, that's getinfo output

**Comment by fr3aker** [comment] 2017-02-22 23:24
sorry, here it is: https://gist.github.com/fr3aker/994c0637d66714352034c4505b4836fb

**Comment by kyuupichan** [comment] 2017-02-22 23:48
Thanks. I'm not at my machine until Sunday, but the thing to understand is why last_connect is not being updated at line 192 of peers.py, or why the peers are not being retried (lines 449-450).

Shouldn't be hard to figure out

**Comment by kyuupichan** [comment] 2017-02-22 23:52
To deug I suggest inserting some strategic log output, such as which peers are being retried, and reducing the retry period from 86400 seconds to 3600.

**Comment by fr3aker** [comment] 2017-02-23 00:54
Is the semaphore at [peers.py#471](https://github.com/kyuupichan/electrumx/blob/master/server/peers.py#L471) ever released somewhere?

**Comment by kyuupichan** [comment] 2017-02-23 00:58
Yes, in connection_lost when the connection is closed, or the line above it if the connection fails and there there are no other ports to try.

**Comment by fr3aker** [comment] 2017-02-23 01:14
What happens if [line 496](https://github.com/kyuupichan/electrumx/blob/master/server/peers.py#L496) evaluates to False?

**Comment by kyuupichan** [comment] 2017-02-23 01:22
The the connection was made and connection_lost will be called by the same method of PeerSession. Do you have reason to believe everything is blocked on the semaphore?

**Comment by fr3aker** [comment] 2017-02-23 01:31
I see. No, I don't have a specific reason to believe it's the semaphore.

**Comment by kyuupichan** [comment] 2017-02-24 02:25
No one managed to figure this out? Does it always happen and to everyone, or just sometimes?

**Comment by shsmith** [comment] 2017-02-24 03:35
It has not happened on any of my servers since 0.99.
I have TOR on all of my servers. I wonder if perhaps this is specific to servers without TOR support.
Who else is still seeing this happen? Can you provide logs for the time period before the peers went stale?

**Comment by kyuupichan** [comment] 2017-02-24 03:44
@shsmith thanks. So the claim at the top of the issue is before 0.99 for you?

**Comment by shsmith** [comment] 2017-02-24 16:00
Peers just started to go stale on vps.hsmiths.com. http://vps.hsmiths.com:49001/peers 

Unfortunately I do not have any extra debug logging enabled on this server. This has not happened yet on the server where I have extra debug logging in place.  

It appears that if verification of one peer hangs, it causes all remaining peers to go unverified until the hung verification eventually times out. Maybe we should asynchronously verify all peers rather than doing them sequentially.  Or perhaps we need a timeout to cancel verification if not finished in x minutes.

I need to leave for work now so I can't follow up for some hours.

**Comment by fr3aker** [comment] 2017-02-24 23:33
> Or perhaps we need a timeout to cancel verification if not finished in x minutes.

This is what I think, too. My server hasn't gone stale since adding debug logging but this is the only scenario I can see the stalling happening. Some bad server where connections are not properly terminated and block all oncoming scheduled checks.

**Comment by kyuupichan** [comment] 2017-02-25 03:03
@shsmith I believe peer connectivity is asynchronous and parallel already, and not serial. A few debug logs would confirm that or refute it. The semaphore is there to prevent massive parallel connections in case someone fed you a long list of junk peers.

**Comment by shsmith** [comment] 2017-02-25 04:20
Here is a multi-day sequence showing the verification of the same peer:

`Feb 18 06:57:08 vps electrum: INFO:PeerSession:[14.3.140.101] verified via SSL at 14.3.140.101:50002
Feb 19 06:51:31 vps electrum: INFO:PeerSession:[14.3.140.101] verified via SSL at 14.3.140.101:50002
Feb 20 06:43:34 vps electrum: INFO:PeerSession:[14.3.140.101] verified via SSL at 14.3.140.101:50002
Feb 21 06:38:46 vps electrum: INFO:PeerSession:[14.3.140.101] verified via SSL at 14.3.140.101:50002
Feb 22 07:18:53 vps electrum: INFO:PeerSession:[14.3.140.101] verified via SSL at 14.3.140.101:50002
Feb 23 07:16:22 vps electrum: INFO:PeerSession:[14.3.140.101] verified via SSL at 14.3.140.101:50002
`

Normally each day the verification is a few minutes earlier than the previous day. 
The exception is on Feb 22 when the verification was delayed by 40 minutes.

You can see the full detail of this verification period here: 
https://gist.github.com/shsmith/7d5a7f04366bd686779a5dbb810e860a

In this case it didn't get stuck, but the delays are large enough to make me think that all remaining verifications are blocking on a hung or slow peer session.

> The semaphore is there to prevent massive parallel connections in case someone fed you a long list of junk peers.

Since we limit the number of new peers accepted to 3 per peer, I think we are already protected against that.

**Comment by kyuupichan** [comment] 2017-02-25 04:33
That's a good point, perhaps the semaphore is unnecessary.  I'd like to confirm validation is parallel, I'm pretty sure it is.

**Comment by SuBPaR42** [comment] 2017-02-25 12:39
Late to the party and just scanned the thread so apologies if this is redundant.

1.  I didn't run the peers RPC - just getinfo
2.  I showed 0 (no) "good" peers - 50+ stale IIRC

So I restarted and posted the comment in IRC.

**Comment by kyuupichan** [comment] 2017-02-26 01:57
@bauerj @SuBPaR42 @shsmith @fr3aker I've added logging to 0.99.1; it would be helpful if you ran that and reported anything unusual you see.  It shows how long it took to get the semaphore (if more than a couple of seconds) and how long peer verification takes.

I have confirmed peer verification is asynchronous and parallel, so that is working as expected
I agree with @shsmith that the semaphore is removable, but I want to understand what is causing the current problem before doing so

**Comment by shsmith** [comment] 2017-02-27 05:18
It is just over 24 hours since I loaded 0.99.1 and most peers on vps.hsmiths.com have gone stale again.
The new logging shows very little.
This was the log as of 21:09:
```
Feb 26 07:36:30 vps electrum: INFO:PeerManager:add_peer request received from cluelessperson.com
Feb 26 12:11:37 vps electrum: INFO:PeerManager:add_peer request received from 0.0.0.0
Feb 26 12:11:37 vps electrum: INFO:PeerManager:ports changed for 0.0.0.0
Feb 26 12:49:03 vps electrum: INFO:PeerManager:add_peer request received from 0.0.0.0
Feb 26 12:49:03 vps electrum: INFO:PeerManager:ports changed for 0.0.0.0
Feb 26 17:18:52 vps electrum: INFO:PeerManager:accepted 1/1 new peers of 1 from E_akinbo_org
Feb 26 17:18:52 vps electrum: INFO:PeerManager:accepted 1/1 new peers of 1 from E_akinbo_org_tor
Feb 26 17:32:10 vps electrum: INFO:PeerManager:add_peer request received from he36kyperp3kbuxu.onion
Feb 26 17:32:32 vps electrum: INFO:PeerManager:add_peer request received from he36kyperp3kbuxu.onion
```
The full output of peers rpc is here: https://hastebin.com/ejonodoquv.css
None of the "last try" or "last conn" dates are from today.

Seems to have hung on the very first verification before anything at all could be logged. I suspect the semaphore on the hung verification is blocking all the remaining peers from being verified.

**Comment by kyuupichan** [comment] 2017-02-27 07:26
Thanks. It seems too much of a coincidence to me that, with 8 slots available on the semaphore, all got filled exactly 24hrs ago just when every peer had been verified. 

I think something else is happening but not sure what. Can you confirm the peers.py main loop is running still?  It might have been knocked out by that exception in the other issue. If the loop terminates for any reason it will write out the peers (see the try... finally ) and that will be logged. Is that in your logs for this 24hr period? 

Another way would be to terminate the process. If that produces the log line then it was running all the time.

**Comment by kyuupichan** [comment] 2017-02-27 10:24
I've pushed 0.99.2 with:

* verbose logging; prints before attempting to get the semaphore, and when released.  Each attempt gets a number so easy to tally
* lowered staleness to 1hr from 1day so reconnects happen more often
* semaphore just permits two concurrent connections

This should make it obvious if something is blocked on semaphore, and if so connections to what hold the semaphore.  It should also make it happen more quickly.  Of course once this is resolved I'll remove the verbose logs.  This just isn't triggering for me; perhaps it's O/S specific for some reason

**Comment by shsmith** [comment] 2017-02-27 15:48
> I think something else is happening but not sure what. Can you confirm the peers.py main loop is running still?

When I did the stop RPC for the update to 0.99.2 it logged "wrote 72 peers", so I think the thread was still alive.  I let it run overnight and no additional peers were verified nor were there any more peer messages, other than incoming add_peer requests.  

Sounds like you covered all the possibilities with the new logging in 0.99.2. I'll watch the logs and post as soon as I see something interesting.

**Comment by shsmith** [comment] 2017-02-27 16:10
Seems to have hung already on two of my servers. 
These are symlinked to live logs:
http://vps.hsmiths.com:49001/electrumx.log  
http://electrum.hsmiths.com:49001/electrumx.log 

These are peer rpc snapshots updated every 5 minutes:
http://vps.hsmiths.com:49001/peers
http://electrum.hsmiths.com:49001/peers

Here are the last PeerManager messages on two servers:

vps.hsmiths.com
```
INFO:LocalRPC:[14] RPC [::1]:59828, 53 total
INFO:PeerSession:[hsmiths4fyqlw5xw.onion] verified via SSL over Tor in 6.1s
INFO:PeerManager:connection 50 to hsmiths4fyqlw5xw.onion closed
WARNING:PeerManager:waited 6.9s for connection semaphore
INFO:PeerManager:preparing connection 52 to b.1209k.com
INFO:PeerSession:[raspi.hsmiths.com] verified via SSL at 76.174.26.91:51002 in 1.3s
INFO:PeerManager:connection 51 to raspi.hsmiths.com closed
INFO:PeerManager:preparing connection 53 to electrum.no-ip.org
INFO:MemPool:catchup 69% complete (5,430 txs left)
```

electrum.hsmiths.com
```
INFO:PeerManager:preparing connection 74 to kerzane.ddns.net
INFO:PeerManager:failed connecting to ELEX.blackpole.online at SSL port 50002 in 0.0s: [Errno -2] Name or service not known
INFO:PeerManager:failed connecting to ELEX.blackpole.online at TCP port 50001 in 0.0s: [Errno -2] Name or service not known
INFO:PeerManager:connection 73 to ELEX.blackpole.online failed
INFO:PeerManager:preparing connection 75 to ELEX04.blackpole.online
INFO:PeerManager:failed connecting to kerzane.ddns.net at SSL port 50002 in 0.0s: [Errno -2] Name or service not known
INFO:PeerManager:failed connecting to kerzane.ddns.net at TCP port 50001 in 0.0s: [Errno -2] Name or service not known
INFO:PeerManager:connection 74 to kerzane.ddns.net failed
INFO:PeerManager:preparing connection 76 to crypto.hughw.net

```
I have to leave for work now, but will check back later to see if either recovered.

**Comment by bauerj** [comment] 2017-02-27 16:24
Interestingly, from what I can see in my monitoring, this has never happened on my servers.

**Comment by kyuupichan** [comment] 2017-02-27 16:33
Perhaps this is another Python 3.5.2 vs 3.5.3 thing? I'm running 3.5.3. I think @bauerj is on 3.6.  Is everyone having the issue using 3.5.2 or earlier perchance?

**Comment by bauerj** [comment] 2017-02-27 16:33
Indeed, 3.6.0.

**Comment by shsmith** [comment] 2017-02-28 00:02
The raspberry pi has 3.5.3 and so far has not had this problem.
My two main servers are both Ubuntu 16.04 LTS, which have 3.5.2 baked into the distribution.
I would prefer if there was a way to make this work on 3.5.2 (i.e. work-around the 3.5.2 bugs) rather than introduce a new dependency.

**Comment by shsmith** [comment] 2017-02-28 06:15
I updated both vps.hsmiths.com and electrum.hsmiths.com to python 3.6. I will check report back in the morning if this stopped the stale peers.

**Comment by SuBPaR42** [comment] 2017-02-28 12:09
electrumx-1 is 16.04 LTS and uses 3.5.2 - the problematic version it seems.

"electrumx" and "mooo" are running 16.10 and show version 3.5.2+ and neither have "hung" to this point.

**Comment by kyuupichan** [comment] 2017-02-28 12:18
@SuBPaR42 thanks.  I'm not familiar with linux distros - is your implication that this is a distro version issue, or that it's a python version issue?

**Comment by bauerj** [comment] 2017-02-28 12:30
I'm running 16.04 LTS too, so that can't be the problem.

**Comment by SuBPaR42** [comment] 2017-02-28 12:32
Python issue.  Just illustrating that newer versions are running with > 3.5.2 and are free of issues.

It seems like Python 3.5.2 is the culprit.

**Comment by kyuupichan** [comment] 2017-02-28 12:35
Thanks.  I'm thinking of making 3.5.3 the requirement then, although I would rather not, but working around this will be somewhat ugly.  ElectrumX is new though so I don't feel too bad about that.  @shsmith was an objector but I think he has bitten the bullet of upgrading anyway.

Would anyone object to making (at runtime) 3.5.3 the requirement?

**Comment by kyuupichan** [comment] 2017-02-28 12:36
3.5.2 also had the tor proxy issues with the asyncio API of socket.make_connection that apparently didn't exist in 3.5.3.  It may even be the same underlying cause here.

**Comment by shsmith** [comment] 2017-02-28 15:40
Too early to tell for sure, but looks hopeful that python 3.6 does not have the mass-stale issue. 
Overnight I saw several slow verifications, but all eventually completed or failed.
```
INFO:PeerManager:failed connecting to crypto.hughw.net at TCP port 50001 in 127.4s: Multiple exceptions: [Errno 110] Connect call failed ('107.20.141.131', 50001), [Errno 101] Network is unreachable
INFO:PeerManager:forgetting unreachable peer: crypto.hughw.net
INFO:PeerManager:connection 1166 to crypto.hughw.net failed
WARNING:PeerManager:waited 254.8s for connection semaphore
INFO:PeerManager:preparing connection 1168 to us10.einfachmalnettsein.de
```

**Comment by kyuupichan** [comment] 2017-02-28 20:59
Thanks. Then I'll keep it simple and require 3.5.3 rather than try to code around it

**Comment by kyuupichan** [comment] 2017-02-28 21:20
Reopening until I have committed code to do the check

**Closed** 2017-02-28 22:34 UTC
