### ISSUE TITLE
Error adding MarteXcoin

### ISSUE THREAD

**Issue by marcianovc** [kyuupichan/electrumx#125] opened 2017-02-14 17:47 UTC
add in coins.py:
`class MartexCoin(Coin):
    NAME = "MartexCoin"
    SHORTNAME = "MXT"
    NET = "mainnet"
    GENESIS_HASH = (b'81f998298dc023c13c9b7948f75cd1ab9'
                    b'0b30d7f9d753e7dbdbfb3b00b193e3b')
    P2PKH_VERBYTE = 0x32 # 50d M
    P2SH_VERBYTE = 0x05
    WIF_BYTE = 0xb2 # 178d (50+128)
    TX_COUNT = 8908766
    TX_COUNT_HEIGHT = 1105256
    TX_PER_BLOCK = 10
    RPC_PORT = 51324
    IRC_CHANNEL = "#electrum-mxt"
    IRC_PREFIX = "d_"
    @classmethod
    def header_hash(cls, header):
        '''Given a header return the hash.'''
        import x13_hash as mxthash
        return mxthash.getPoWHash(header)

class MartexCoinTestnet(MartexCoin):
    NET = "testnet"
    GENESIS_HASH = (b'0000bb718576edb7039081063593e532f'
                    b'965022430ba18fae246973715c2afc7')
    P2PKH_VERBYTE = 0x6f
    P2SH_VERBYTE = 0xc4
    WIF_BYTE = 0xef
    RPC_PORT = 41324
    IRC_CHANNEL = "#electrum-mxt"
    IRC_PREFIX = "dt_"
    def header_hash(cls, header):
        '''Given a header return the hash.'''
        import x13_hash as mxthash
        return mxthash.getPoWHash(header)
`

@4000000058a33f9a09b4c784 Launching ElectrumX server...
@4000000058a33f9a20c1085c INFO:root:ElectrumX server starting
@4000000058a33f9a20e326bc INFO:Daemon:daemon #1 at localhost:41324/ (current)
@4000000058a33f9a20e75124 INFO:BlockProcessor:switching current directory to /db-electrumx
@4000000058a33f9a21d86fb4 INFO:BlockProcessor:using leveldb for DB backend
@4000000058a33f9a23bb6854 INFO:BlockProcessor:opened DB for serving
@4000000058a33f9a23bd7b94 INFO:BlockProcessor:closing DB to re-open for sync
@4000000058a33f9a253a2c9c INFO:BlockProcessor:opened DB for sync
@4000000058a33f9a253c1cb4 INFO:BlockProcessor:software version: ElectrumX 0.10.18
@4000000058a33f9a253d7474 INFO:BlockProcessor:DB version: 5
@4000000058a33f9a253eb4c4 INFO:BlockProcessor:coin: MartexCoin
@4000000058a33f9a253fe18c INFO:BlockProcessor:network: testnet
@4000000058a33f9a2541123c INFO:BlockProcessor:height: -1
@4000000058a33f9a25426614 INFO:BlockProcessor:tip: 0000000000000000000000000000000000000000000000000000000000000000
@4000000058a33f9a254392dc INFO:BlockProcessor:tx count: 0
@4000000058a33f9a2544ee84 INFO:BlockProcessor:sync time so far: 00s
@4000000058a33f9a2547e06c INFO:BlockProcessor:reorg limit is 200 blocks
@4000000058a33f9a254c0ad4 INFO:BlockProcessor:flushing DB cache at 1,200 MB
@4000000058a33f9a2667a464 INFO:Prefetcher:catching up to daemon height 70,145 (70,146 blocks behind)
@4000000058a33f9a27b23564 ERROR:Controller:Traceback (most recent call last):
@4000000058a33f9a27b23d34   File "/electrumx/server/controller.py", line 225, in on_future_done
@4000000058a33f9a27b23d34     future.result()
@4000000058a33f9a27b2411c   File "/electrumx/server/block_processor.py", line 49, in main_loop
@4000000058a33f9a27b2411c     if not await self._prefetch_blocks():
@4000000058a33f9a27b24504   File "/electrumx/server/block_processor.py", line 105, in _prefetch_blocks
@4000000058a33f9a27b248ec     blocks = await daemon.raw_blocks(hex_hashes)
@4000000058a33f9a27b28384   File "/electrumx/server/daemon.py", line 177, in raw_blocks
@4000000058a33f9a27b2876c     return [bytes.fromhex(block) for block in blocks]
@4000000058a33f9a27b2876c   File "/electrumx/server/daemon.py", line 177, in <listcomp>
@4000000058a33f9a27b28b54     return [bytes.fromhex(block) for block in blocks]
@4000000058a33f9a27b28b54 TypeError: fromhex() argument must be str, not dict

**Comment by bauerj** [comment] 2017-02-14 19:02
It seems like the daemon is misbehaving.

What does  `getblock(0000bb718576edb7039081063593e532f965022430ba18fae246973715c2afc7, false)` return?

Also, please try to get your code in some kind of readable form: [Mastering Markdown 🕐 3 minute read ](https://guides.github.com/features/mastering-markdown/).

**Comment by kyuupichan** [comment] 2017-02-14 21:21
Looks like your daemon doesn't respond as expected to the get block call. No idea what they changed, you'll need to figure that out for yourself.

**Comment by kyuupichan** [comment] 2017-02-15 23:03
Closing this - the issue is that your coin is not compatible with bitcoin for RPC and / or block format.  You will need to find out what's changed and modify the code accordingly.  If it's not too intrusive I will accept a pull request to implement it.

**Closed by kyuupichan** 2017-02-15 23:03 UTC

**Comment by knkrth** [comment] 2017-10-18 03:44
I also got the same error with `getblock(0000bb718576edb7039081063593e532f965022430ba18fae246973715c2afc7, false)` it retunes `-bash: syntax error near unexpected token '('` But without brackets      
`getblock 0000bb718576edb7039081063593e532f965022430ba18fae246973715c2afc7, false'` retunes value.

**Comment by marcianovc** [comment] 2019-04-05 20:50
```
Apr  5 22:43:51 vmi188072 systemd[1]: Started Electrumx.
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:Controller:Python version: 3.6.4 (default, Jul 17 2018, 15:08:31)
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: [GCC 6.3.0 20170516]
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:Controller:software version: ElectrumX 1.10.0
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:Controller:aiorpcX version: 0.10.5
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:Controller:supported protocol versions: 1.2-1.4.1
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:Controller:event loop policy: None
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:Controller:reorg limit is 200 blocks
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:Daemon:daemon #1 at localhost:52314/ (current)
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:DB:switching current directory to /root/.electrumx/
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:DB:using leveldb for DB backend
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:DB:opened UTXO DB (for sync: True)
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:DB:DB version: 6
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:DB:coin: MarteXcoin
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:DB:network: mainnet
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:DB:height: -1
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:DB:tip: 0000000000000000000000000000000000000000000000000000000000000000
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:DB:tx count: 0
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:DB:flushing DB cache at 1,800 MB
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:DB:sync time so far: 00s
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:History:history DB version: 0
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:History:flush count: 0
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:SessionManager:RPC server listening on localhost:8001
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:Prefetcher:catching up to daemon height 1,568,880 (1,568,881 blocks behind)
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:Prefetcher:verified genesis block with hash 617fc383b07fbab3505213b41fe34f9705b92d854a9f72593cb616e4726e155c
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:BlockProcessor:flushing to DB for a clean shutdown...
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: INFO:SessionManager:closing down RPC listening servers
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: ERROR:root:task crashed: <Task finished coro=<Controller.serve() done, defined at /root/electrumx/electrumx/server/controller.py:81> exception=AssertionError()>
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: Traceback (most recent call last):
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/usr/local/lib/python3.6/site-packages/aiorpcX-0.10.5-py3.6.egg/aiorpcx/util.py", line 119, in check_task
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     task.result()
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/server/controller.py", line 134, in serve
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     await group.spawn(wait_for_catchup())
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/usr/local/lib/python3.6/site-packages/aiorpcX-0.10.5-py3.6.egg/aiorpcx/curio.py", line 240, in __aexit__
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     await self.join()
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/usr/local/lib/python3.6/site-packages/aiorpcX-0.10.5-py3.6.egg/aiorpcx/curio.py", line 207, in join
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     raise task.exception()
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/server/block_processor.py", line 658, in fetch_and_process_blocks
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     await group.spawn(self._process_prefetched_blocks())
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/usr/local/lib/python3.6/site-packages/aiorpcX-0.10.5-py3.6.egg/aiorpcx/curio.py", line 240, in __aexit__
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     await self.join()
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/usr/local/lib/python3.6/site-packages/aiorpcX-0.10.5-py3.6.egg/aiorpcx/curio.py", line 207, in join
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     raise task.exception()
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/server/block_processor.py", line 619, in _process_prefetched_blocks
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     await self.check_and_advance_blocks(blocks)
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/server/block_processor.py", line 201, in check_and_advance_blocks
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     for n, raw_block in enumerate(raw_blocks)]
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/server/block_processor.py", line 201, in <listcomp>
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     for n, raw_block in enumerate(raw_blocks)]
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/lib/coins.py", line 249, in block
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     txs = cls.DESERIALIZER(raw_block, start=len(header)).read_tx_block()
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/lib/tx.py", line 134, in read_tx_block
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     return [read() for _ in range(self._read_varint())]
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/lib/tx.py", line 134, in <listcomp>
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     return [read() for _ in range(self._read_varint())]
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/lib/tx.py", line 124, in read_tx_and_hash
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     return self.read_tx(), self.TX_HASH_FN(self.binary[start:self.cursor])
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/lib/tx.py", line 112, in read_tx
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     self._read_inputs(),    # inputs
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/lib/tx.py", line 138, in _read_inputs
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     return [read_input() for i in range(self._read_varint())]
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/lib/tx.py", line 138, in <listcomp>
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     return [read_input() for i in range(self._read_varint())]
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/lib/tx.py", line 144, in _read_input
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     self._read_varbytes(),   # script
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/lib/tx.py", line 170, in _read_varbytes
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     return self._read_nbytes(self._read_varint())
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:   File "/root/electrumx/electrumx/lib/tx.py", line 166, in _read_nbytes
Apr  5 22:43:51 vmi188072 electrumx_server[7709]:     assert self.binary_length >= end
Apr  5 22:43:51 vmi188072 electrumx_server[7709]: AssertionError
```

electrumx/lib/coins.py:

```
class MarteXcoin(Coin):
    NAME = "MarteXcoin"
    SHORTNAME = "MXT"
    NET = "mainnet"
    XPUB_VERBYTES = bytes.fromhex("0488B21E")
    XPRV_VERBYTES = bytes.fromhex("0488ADE4")
    P2PKH_VERBYTE = bytes.fromhex("32")
    P2SH_VERBYTES = bytes.fromhex("05")
    WIF_BYTE = bytes.fromhex("b2")
    GENESIS_HASH = '617fc383b07fbab3505213b41fe34f97' \
                   '05b92d854a9f72593cb616e4726e155c'
    TX_COUNT = 8908766
    TX_COUNT_HEIGHT = 1105256
    TX_PER_BLOCK = 10
    RPC_PORT = 51314
    PEERS = []

    @classmethod
    def header_hash(cls, header):
        '''Given a header return the hash.'''
        import x13_hash
        return x13_hash.getPoWHash(header)

```
