### ISSUE TITLE
High CPU usage, clients reconnecting

### ISSUE THREAD

**Issue by whizz** [kyuupichan/electrumx#781] opened 2019-04-02 08:16 UTC
I have been running ElectrumX for a long time (several years). Recently, I am seeing quite high CPU usage and I am having trouble connecting to the server with Electrum wallet. When I run the wallet with "-v" flag, I am seeing that the "blockchain.estimatefee" is timing out, which causes the wallet to disconnect and reconnect again. I assume this is increasing the load on the server, because the amount of work at connection time is much higher than during idle.

The same thing is also happening to other people using my server apparently, because I am seeing a large number of connect entries in the log, much more than previously, repeatedly from same IP addresses.

Any ideas how to investigate further? Am I the only one seeing this? I am running 0.10.0 and the server is powerful enough, it has 8 cores. ElectrumX is eating about 2 cores.

**Comment by xA8EYLgMSN43oEHC** [comment] 2019-04-02 10:10
I'm seeing high read io on mine. A couple of threads stays pinned at 99% which saturates the disk completely, which in turn makes ElectrumX unusable.
electrumx-1.10.0

**Comment by whizz** [comment] 2019-04-03 12:16
> I'm seeing high read io on mine.

Yes, that too. In fact, I did not notice it before, but electrumx is doing about 500 MB/s constant reads.

**Comment by peleion** [comment] 2019-04-03 14:37
There is an ongoing DoS attack against public servers and this sounds likely in your case. Is it publicly available? I had similar problems until I took several steps to mitigate:

1. SSL connections only - a large amount of DoS appears to target TCP port 50001 (ease of scripting?). Electrum wallet defaults to SSL anyway and I don't see a drop in users
2. Enable syncookies in the kernel in /etc/sysctl.conf. There appears to be a large amount of syn flooding occuring using a botnet and is nearly impossible to effectively block other than at the firewall. 
3. MAX_SEND: '350000' and MAX_SESSION_SUBS: '5000' serves all but the biggest clients. Attackers seem to be repeatedly connecting to wallets in order to tie up servers. I realize this negatively impacts clients with wallets >1,000 simple transactions but that is a very small number of users. If a whale connects they only tie up the server for a few minutes and disconnect - I haven't noticed any constant reconnects. 
4. I personally block Digital Ocean CIDR IP ranges using ipset/iptables as most of the sybil abuse appears to originate from there. Again, this prevents some legitimate connections but vastly reduces DoS

Right now my public server has 666 clients with average load about 1.0 and no problems connecting. Your mileage may vary and you may not wish to take some of these steps but they helped me. I'm just a community member running a public server and have no ties to Neal or the ElectrumX project - this is not "official" advice.

**Comment by whizz** [comment] 2019-04-03 15:43
Thanks @peleion, I suspected something like that. 

re 1) I have only SSL enabled. 
re 2) the problem is not syn flooding, or any other low level network DoS. I have the syncookies enabled anyway.
re 3) I did this now, but it does not seem to help. If I list the sessions, none of them have any significant number of subs, so I guess the attack has some other form, maybe querying hashes without subscribing. Anyone knows if there is some kind of debug logging, that can be enabled, to trace what rpc calls individual clients are sending? Or somehow rate limit it?
re 4) I do not see any significant activity from Digital Ocean,

**Comment by peleion** [comment] 2019-04-04 17:42
I dunno. My theory is that the attackers may get the server list from the DO peer list for targets then forward it to the botnet. Your server is probably already on their list and may not show immediate improvement. All I am sure of is that my troubles decreased 99% when implementing these steps. 

My blacklist is [here](https://electrum.peleion.com/blacklist.txt) and includes a small known Lithuanian attack source and the Chinese search engine Badiu (who is very rude). 

Ghost43 had a patch for E-X to log everything to diagnose s7r's problem a while back but I don't think there is any verbose logging available on stock E-X or rate limiting. Would be nice to add, I don't have the python chops to write a pull.

**Comment by SomberNight** [comment] 2019-04-04 17:46
Most public e-x servers are being DDOS-ed using a new methodology. The attack is non-trivial; it consists of multiple things, but it's mostly on the application layer. We are trying to figure out how to mitigate it best.

**Comment by SomberNight** [comment] 2019-04-05 01:00
See https://github.com/kyuupichan/electrumx/pull/785

**Comment by kyuupichan** [comment] 2019-04-06 23:08
Closing this; the cause is external

**Closed by kyuupichan** 2019-04-06 23:08 UTC
