### ISSUE TITLE
Super slow sync starting around 400k

### ISSUE THREAD

**Issue by mzarglis** [kyuupichan/electrumx#958] opened 2020-02-14 18:19 UTC
Electrumx V 1.14.0
Core i3 7300 (Dual core w/ HT  4Ghz)
8GB Ram (no swap enabled)
Electrumx DB and full bitcoin chain on 1TB samsung SSD
DB_CACHE 1800

The sync get to block 400k in about 5 hours but from blocks 400k+ sync slows down dramatically. Is this expected? I read through the documentation and it seemed like the sync time should be relatively linear from blocks 280K+.
![Untitled](https://user-images.githubusercontent.com/994599/74556718-a98d8180-4f2c-11ea-90f3-26e9b3ee14ed.png)

**Comment by kyuupichan** [comment] 2020-02-14 21:12
It should be somewhat linear, yes.  However the speed depends very much on what's in your OS's page/file cache, and so if e.g. you're running two instances of ElectrumX on one machine, one can get into a state where it is (OS) cache-starved by the other, and even though it's the same software on the same box, one can be much fast than the other.  Only you know what you're running on your box...

Anyway closing as this is not a bug in the software

**Closed by kyuupichan** 2020-02-14 21:12 UTC

**Comment by kyuupichan** [comment] 2020-02-14 21:13
You can try shutting down ElectrumX and restarting.  However as I said the real issue is what is hot-cache in your O/S, which is a function of what else you're running on the same machine.

**Comment by mzarglis** [comment] 2020-02-16 17:45
So is this something more ram can fix / help speed up

**Comment by mzarglis** [comment] 2020-02-16 18:03
> 
> 
> It should be somewhat linear, yes. However the speed depends very much on what's in your OS's page/file cache, and so if e.g. you're running two instances of ElectrumX on one machine, one can get into a state where it is (OS) cache-starved by the other, and even though it's the same software on the same box, one can be much fast than the other. Only you know what you're running on your box...
> 
> Anyway closing as this is not a bug in the software

So is this something more ram can fix / help speed up

**Comment by mzarglis** [comment] 2020-04-14 18:35
Upping my memory so the system would cache more of the DB in ram helped significantly to any others who experience slow syncs
