### ISSUE TITLE
Be honest about supporting only AltcoinSV

### ISSUE THREAD

**Issue by sumBTC** [kyuupichan/electrumx#1018] opened 2020-06-04 09:22 UTC
I wanted to upgrade ElectrumX to version 1.15.0. To my surprise I got an error message about the "COIN=BitcoinSegwit" variable. I consulted the documentation for [1.15.0](https://electrumx.readthedocs.io/en/latest/environment.html#required) and only found:

COIN

    Must be a NAME from one of the Coin classes in lib/coins.py.

all I could find in `lib/coins.py` was AltcoinSV. 

To add to the confusion you state that:

`Version 1.15.0 will be the final ElectrumX release with altcoin support, future releases will be Bitcoin-only.`

while it is AltcoinSV only. I wasted a lot of time on this.

Bitcoin only updates the difficulty every 2016 blocks. AltcoinSV has difficulty adjustments in the software and is therefore an altcoin or a double spend attempt on Bitcoin. That's my opinion at least. **If you only want to support AltcoinSV that's fine with me (it's a free world) but at least be open about it. Now it looks like a scam.**

*Also point to the version that's still supporting Bitcoin: https://github.com/spesmilo/electrumx*

Thanks for all your hard work on Electrumx much appreciated but you're not the CEO of Bitcoin. I'm sorry it had to end like this but I wish you all the best.

**Comment by oitdmser** [comment] 2020-06-06 22:14
Agreed. It's short-sighted and very saddening that you would chose to support the weak fork of a fork of Bitcoin, but say in your documentation that v1.15 is the last to support 'altcoins.' At least be clear that you're only supporting BitcoinSV. Even SV fanatics agree that Bitcoind != BitcoinSV, and interchanging the names to further some agenda or from some bigoted viewpoint is bad for BOTH, but since SV is the smaller, weaker chain, it has much more to lose.

**Comment by smmalis37** [comment] 2020-06-08 05:29
See also #1014 and #1015.

**Comment by rmwb** [comment] 2020-06-10 02:29
FYI the v1.15.0 that still supports Bitcoin is in the 'altcoin' branch:
https://github.com/kyuupichan/electrumx/tree/altcoin

**Comment by cculianu** [comment] 2020-06-25 08:05
The Electrum authors are also supporting their own officially: https://github.com/spesmilo/electrumx

**Comment by ser** [comment] 2020-07-09 09:01
I really can't believe this shit

**Comment by cculianu** [comment] 2020-07-09 09:34
In his defense it’s free software. Anyone is free to fork it.

Likely there are scaling challenges With supporting the specific things BSV wants to do and it may be a burden to support all coins.

The existing electrumx should work ok for the time being and there is the bitcoin fork presented above.  It is what it is. It’s free software and kyuupichan is a volunteer. All things considered this is fair.

**Comment by smmalis37** [comment] 2020-07-09 09:48
@cculianu Most people here aren't complaining about his choice in coin support, but rather the deliberately misleading documentation accompanying it (and that honest attempts to fix it are dismissed #1015) . I agree that kyuupichan can do what he wants with his repo, but lying to people is not ok, and lying about something that you hold a financial stake in is especially not ok.

**Comment by cculianu** [comment] 2020-07-09 10:05
Don’t you feel like lying is a strong word? He literally did his best to support almost every coin under the sun for years. He has a change of course. Maybe he didn’t have time to update everything. The man did great work for years and it’s just him. He’s not Apple or Microsoft. It’s literally mostly him. Maybe he forgot to update the docs. I don’t think he is intentionally being deceptive. That’s not his nature as far as I know.

**Comment by cculianu** [comment] 2020-07-09 10:07
Update: oh I see the irritation is with the term bitcoin. BSV people believe that BSV is the true bitcoin. 

I don’t know what to say about that except that as a person who has abandoned bitcoin BTC years ago — I can understand the sentiment.

**Comment by sumBTC** [comment] 2020-07-09 11:20
@cculianu  `GOTO: @smmalis37`

**Comment by ser** [comment] 2020-07-09 14:33
you are really funny @cculianu - you must be a king of comedy shows

**Comment by cculianu** [comment] 2020-07-09 14:42
Ha ha, I try. :)

**Comment by pioruns** [comment] 2020-07-10 23:25
What is this? Please close this "issue" - it's not a bug. Bitcoin "faketoshi" SV fanatics, just go.

**Comment by pioruns** [comment] 2020-07-10 23:38
This project going rogue, supporting only faketoshi version of Bitcoin? So be it.
Already moved live db and files over to https://github.com/spesmilo/electrumx. Everything works perfectly.
Goodbye Craig Wright and his fake coin.

**Comment by CodeForcer** [comment] 2020-10-22 17:53
This is really upsetting, this was a great repository.

**Closed** 2020-11-03 01:26 UTC

**Comment by curious0101** [comment] 2020-11-03 01:31
Garbage.

**Comment by cculianu** [comment] 2020-11-11 11:12
If you guys want I made my Fulcrum server support BTC now. It has a feature set very similar to ElectrumX and should feel familiar to users already accustomed to running ElectrumX.

You can get it here: https://github.com/cculianu/Fulcrum

While it's written in C++ and needs to be compiled, I do provide static precompiled binaries.  Check the releases page above where I provide the pre-built static binaries.

**Comment by smmalis37** [comment] 2020-11-11 11:14
I think most of us have just moved to https://github.com/spesmilo/electrumx, but more diversity and options are always appreciated!
