### ISSUE TITLE
JSON RPC request fails when HTTP headers are present

### ISSUE THREAD

**Issue by MorbZ** [kyuupichan/electrumx#144] opened 2017-03-09 15:21 UTC
I'm trying to query the JSON RPC interface of ElectrumX from an own Python script, however I always get the error:

`cannot decode JSON: Expecting value: line 1 column 1 (char 0)`

Further research showed that most(/all) JSON RPC libraries for Python that I could find use the HTTP protocol, so they add headers before the JSON payload. A sample request looks like this:

```
POST / HTTP/1.1
Host: localhost:8000
Accept-Encoding: gzip
User-Agent: jsonrpclib/0.1 (Python 2.7.10)
Content-Type: application/json-rpc
Content-Length: 57

{"jsonrpc": "2.0", "id": "k5wodffn", "method": "getinfo"}
```

It seems ElectrumX is trying to parse the whole message as JSON, including the HTTP headers, which leads to a fail of course. It would be good if ElectrumX would ignore the headers and only uses everything after the double newline as the JSON payload.

**Comment by kyuupichan** [comment] 2017-03-09 15:25
This is not a bug.  It is not an HTTP connection, it is a plain TCP connection.

**Comment by MorbZ** [comment] 2017-03-09 15:28
I didn't say it's a bug. However it would be nice if the RPC interface would be compatible to the majority of the JSON RPC clients out there.

**Comment by kyuupichan** [comment] 2017-03-09 15:29
It is also not how the original Electrum server worked.  Maybe the clients should expose the actual JSON RPC guts and not an HTTP wrapped version?

**Comment by kyuupichan** [comment] 2017-03-09 15:30
ElectrumX comes with its own JSON RPC library for clients and servers, as it uses it for peer-to-peer connections as a client.  But I won't claim it is finished or ideal, yet.

**Comment by MorbZ** [comment] 2017-03-09 16:08
> It is also not how the original Electrum server worked. Maybe the clients should expose the actual JSON RPC guts and not an HTTP wrapped version?

Are you aware of a library that is capable of doing this? I haven't found one yet.

> ElectrumX comes with its own JSON RPC library for clients and servers, as it uses it for peer-to-peer connections as a client. But I won't claim it is finished or ideal, yet.

I can't use it unfortunately since I'm using Python 2.

**Comment by kyuupichan** [comment] 2017-03-12 01:50
I don't see how ignoring some header would work either.  Clearly the client is expecting HTTP to be spoken, and so will expect an HTTP response too.

If you want to extend ElectrumX to accept HTTP connections I probably wouldn't object, but it would have to be done properly (i.e. not just skipping some arbitrary text).  I won't be working on such a thing myself.

**Comment by erasmospunk** [comment] 2017-03-18 02:37
It seems the JSON RPC library that @MorbZ is using is expecting a request/response style of communication (HTTP/1.1). In this case the `*.subscribe` methods will not work because the server cannot send data at any point without there being a request from the client first.

**Comment by MorbZ** [comment] 2017-03-21 21:51
@erasmospunk I just mean the RPC interface for the server commands like getinfo/sessions/peers etc.

**Comment by kyuupichan** [comment] 2017-03-21 23:21
@MorbZ why would you just use the provided script?

**Comment by MorbZ** [comment] 2017-03-22 19:29
@kyuupichan Can't use the script because I'm using Python 2. It seems it's common practice to wrap JSON RPC in HTTP, probably to make it available for tools like wget/curl. Bitcoin Core even requires HTTP. I'm using plain sockets now to query ElextrumX which works just fine, but HTTP support would be appreciated.

**Comment by kyuupichan** [comment] 2017-03-22 23:05
I see.  I don't really want to add the complexity of another port, more env vars, and supporting HTTP requests simply because someone has Python2 and not Python3.  The server itself requires Python3, though I realise it can be on a different machine.

So I'll close this.

**Closed by kyuupichan** 2017-03-22 23:05 UTC

**Comment by stefanhuber** [comment] 2017-03-28 12:40
Support for http(s) would although be absolutely great ;)
